### PR TITLE
feat: Foundry Port

### PR DESCRIPTION
**Pull request by abigger87**

### CODE REVIEW

**Comment by devtooligan** [comment]
whats the relationship between this repo and huffmates.  for example how will the erc20 in this repo differ from huffmate?  which repo do we encourage contributors to use?

**Comment by abigger87** [comment]
> whats the relationship between this repo and huffmates.  for example how will the erc20 in this repo differ from huffmate?  which repo do we encourage contributors to use?

This is a good question, currently it is not obvious even after digesting the READMEs of both repos. The distinction is intended to be that huff-examples contain fully working, instantiable contracts (think: the mock contracts of huffmate). Whereas huffmate contains **building blocks** for creating contracts - they themselves are not instantiable.

Will make this distinction clear in this branches readme before merging.

**Comment by abigger87** [comment]
Further - I think it's important to have both as one serves as a way to fully understand huff contracts, whereas the other (huffmate) serves as a devtool.

Especially given the fact that huff in general is such a low-level language, it makes sense to push out as many fleshed out (well tested, heavily documented, and standardized) contracts as possible IMO

**Comment by abigger87** [comment]
> thats a v clear explanation. so if thats the case should these ctrcts import the huffmate "abstract" ctrcts?

Yooo, yes that's a great idea. Will implement in this branch. Great point!

**Pull request merged**
